---
language: java

sudo: required

services:
  - docker

before_install:
  - docker pull lukasmartinelli/hadolint
  - docker pull koalaman/shellcheck:stable

jobs:
  include:
    - stage: "Syntax"
      name: "Dockerfile checks with Hadolint"
      script: docker run --rm -i lukasmartinelli/hadolint hadolint - < src/main/Dockerfile
    -
      name: "Shell checks with shellchecker"
      script: docker run -v "$(pwd)":/mnt koalaman/shellcheck:stable src/main/*sh
    - stage: "Integration Tests"
      name: "docker-maven-plugin integration tests"
      script: mvn verify
