---
language: java

sudo: required

services:
  - docker

before_install:
  - docker pull lukasmartinelli/hadolint
  - docker pull koalaman/shellcheck:stable
  - secure: "jKMFGbNnC5WeDvC8tjl9x0wyhtkoipgmIhDSEvlpfq8ceUyolTm/q1M2CMkJ1aMIXNXPe70GX6BE9t7vCLJDVPrVwXHNh4FZYTUNMEncqWCZqOeakhYRf3UFKNYYcvzqNx97LWSuFZt6aSJCdq/VxlSWsfE+Bgk9ZCUwJaPJJDzkxqPcV+W2YsCZbHZAZS5GmZHRzKvvvphwyB9RKb2VOr6j8OzsshtCri8EJ+rra7FMPtZ6AVIsBsQLYcy+XOGZzlkZfOuw5bS3pOiOGPqZu8zsLmP26W6I/MoayH8mc+PljrLW4I9JmsuB6JZez7R0q/87PfSg8KytmDHnJ9S6RsntxrHbsGuuyyq0bZISebW7Xq8YDNq/sSuxV82erid8PbsM2Cgwk7Yegc0QUIFb5paUDcd2pJeSPfiF3+7lteQpqpDz9eP4mkxLQU5+KjUchRUpEaW5BxCzqQ73N6SJqZq7YIfzvHUSrgMltBc2cT7/DvBu9NQNfbsqRlAn7MRhU1ZIbWgN+tKb2d7libHVXjomTEGhdL4J6OSJs8wXtpHboWbKPjwuv5KJPLFMcAB0QdVSHwh5x2d87xB0l8PMRcnzEO1WVRV4XwX5PWU0VjUYqK7CCxPkSbpXW1yQ/BJCVX7H1Umo7xWyMn3vCfbtwXHAwtrhBhyglof8mDEz3FI="

jobs:
  include:
    - stage: "Syntax"
      name: "Dockerfile checks with Hadolint"
      script: docker run --rm -i lukasmartinelli/hadolint hadolint - < src/main/Dockerfile
    -
      name: "Shell checks with shellchecker"
      script: docker run -v "$(pwd)":/mnt koalaman/shellcheck:stable src/main/*sh
    - stage: "Integration Tests"
      name: "docker-maven-plugin integration tests"
      script: mvn verify
    - stage: "Deploy"
      name: "Deploy to DockerHub"
      script: mvn docker:push
